theme: jekyll-theme-minimal
url: "https://huiquanr.github.io"
baseurl: ""
title: "Tony Huiquan Zhang | 张汇泉"
description: "Tony Huiquan Zhang (张汇泉), sociologist, researcher and Mandarin pop lyricist."
